version: 2
 
sources:
 - name: conformed
   database: raw
   schema: conformed
 
   tables:
     - name: DateDimension
       columns:
         - name: DateKey
           tests:
             - unique
 
 - name: events_projectdb
   database: raw
   schema: myEvent_v1
 
   tables:
     - name: zipcodes
       columns:
         - name: zipcode
           tests:
             - unique
 
     - name: organization_type_lookup
       columns:
         - name: org_type_name
           tests:
             - unique
 
     - name: organizations
       columns:
         - name: organization_id
           tests:
             - unique
 
     - name: type_of_services
       columns:
         - name: type_id
           tests:
             - unique
         - name: type_name
           tests:
             - unique
 
     - name: services
       columns:
         - name: service_id
           tests:
             - unique
         - name: my_service_name
           tests:
             - unique
 
     - name: service_type
       tests:
         - dbt_utils.unique_combination_of_columns:
             combination_of_columns:
               - service_id
               - type_id
 
     - name: venues
       columns:
         - name: venue_id
           tests:
             - unique
         - name: venue_name
           tests:
             - unique
 
     - name: request_statuses
       columns:
         - name: status_type
           tests:
             - unique
 
     - name: event_types
       columns:
         - name: event_type
           tests:
             - unique
 
     - name: requests
       columns:
         - name: request_id
           tests:
             - unique
         - name: request_event_name
           tests:
             - unique
 
     - name: events
       columns:
         - name: event_id
           tests:
             - unique
         - name: event_name
           tests:
             - unique
 
     - name: people
       columns:
         - name: person_id
           tests:
             - unique
         - name: person_email
           tests:
             - unique
 
     - name: reviews
       columns:
         - name: review_id
           tests:
             - unique
         - name: review_text
           tests:
             - unique
 
     - name: tickets
       columns:
         - name: ticket_id
           tests:
             - unique